#!/usr/bin/env python3
# ------------------------------------------------------------------------------
# Prepends the testfile name to the output files generated by dhat and callgrind.
# ------------------------------------------------------------------------------
import re
import os
from pathlib import Path

def rename(tool: str):
    if tool.lower() == "dhat":
        cmd_line = 5
    elif tool.lower() == "callgrind":
        cmd_line = 4
    else:
        print(f"Unknown tool: {tool}")
        return

    for file in Path('.').glob(f'{tool}.out.*'):   
        try:
            with open(file, 'r') as f:
                lines = f.readlines()
                if len(lines) < cmd_line + 1:
                    print(f"File {file} might be empty, rerun analysis")
                    continue
                line = lines[cmd_line]
                
                if file.name.startswith(f'{tool}.out.miri'):
                    # extract the test name after --crate-name
                    match = re.search(r'--crate-name\s+(\S+)', line)
                    if match:
                        test = match.group(1)
                        new_name = f"{test}.{file.name}"
                        print(f"Renaming {file} -> {new_name}")
                        file.rename(new_name)
                    else:
                        print(f"Deleting {file} ({" ".join(line.split()[:2])})")
                        file.unlink()

                else: # default (no miri)
                    if 'cargo test' not in line:
                        if tool.lower() == "dhat":
                            match = re.search(r'"cmd":"([^"]+)"', line)
                        else: # callgrind
                            match = re.search(r'cmd:\s+([^\s]+)', line)
                        if match:
                            cmd = match.group(1)
                            
                            # trim around the cmd
                            basename = cmd.split('/')[-1]
                            test = basename.split('-')[0]
                            
                            if test:
                                new_name = f"{test}.{file.name}"
                                print(f"Renaming {file} -> {new_name}")
                                file.rename(new_name)
                            else:
                                print(f"there was no test {line}, {test}")
                    else:
                        print(f"Deleting {file} ({" ".join(line.split()[:3])})")
                        file.unlink()
        except Exception as e:
            print(f"Error processing {file}: {e}")

rename("dhat")
rename("callgrind")