#!/usr/bin/env python3
# ------------------------------------------------------------------------------
# Prepends the testfile name to the output files generated by dhat and callgrind.
# Copies renamed files to a new folder in profiling/
# ------------------------------------------------------------------------------
import re
import sys
import shutil
from pathlib import Path

def rename(tool: str, project_dir: Path, output_dir: Path):
    if tool.lower() == "dhat":
        cmd_line = 5
    elif tool.lower() == "callgrind":
        cmd_line = 4
    else:
        print(f"Unknown tool: {tool}")
        return
    
    tool_output_dir = output_dir / tool.lower()
    tool_output_dir.mkdir(exist_ok=True)

    for file in project_dir.glob(f'{tool}.out.*'):   
        try:
            with open(file, 'r') as f:
                lines = f.readlines()
                if len(lines) < cmd_line + 1:
                    print(f"!!! File {file} might be empty, rerun analysis")
                    continue
                line = lines[cmd_line]
                
                if file.name.startswith(f'{tool}.out.miri'):
                    # extract the test name after --crate-name
                    match = re.search(r'--crate-name\s+(\S+)', line)
                    if match:
                        test = match.group(1)
                        new_name = f"{test}.{file.name}"
                        dest_path = tool_output_dir / new_name
                        print(f"Copying {file} -> {dest_path}")
                        shutil.copy2(file, dest_path)
                    else:
                        print(f"Skipping {file} ({' '.join(line.split()[:2])})")

                else: # default (no miri)
                    if 'cargo test' not in line:
                        if tool.lower() == "dhat":
                            match = re.search(r'"cmd":"([^"]+)"', line)
                        else: # callgrind
                            match = re.search(r'cmd:\s+([^\s]+)', line)
                        if match:
                            cmd = match.group(1)
                            
                            # trim around the cmd
                            basename = cmd.split('/')[-1]
                            test = basename.split('-')[0]
                            
                            if test:
                                new_name = f"{test}.{file.name}"
                                dest_path = tool_output_dir / new_name
                                print(f"Copying {file} -> {dest_path}")
                                shutil.copy2(file, dest_path)
                            else:
                                print(f"!!! there was no test? {line}, {test}")
                    else:
                        print(f"Skipping {file} ({' '.join(line.split()[:3])})")
        except Exception as e:
            print(f"!!! Error processing {file}: {e}")

def main():
    if len(sys.argv) != 2:
        print("Usage: python3 copy_outputs.py <project_folder>")
        sys.exit(1)
    
    project_dir = Path(sys.argv[1])
    
    if not project_dir.exists() or not project_dir.is_dir():
        print(f"Error: {project_dir} is not a valid directory")
        sys.exit(1)
    
    folder_name = project_dir.name.split('-')[0] + "-outputs"
    
    # create output directory in cwd
    output_dir = Path.cwd() / folder_name
    output_dir.mkdir(exist_ok=True)
    
    rename("dhat", project_dir, output_dir)
    rename("callgrind", project_dir, output_dir)
    
    print(f"\nDone! Renamed files copied to: {output_dir}")

if __name__ == "__main__":
    main()